### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###
@url = http://localhost:3000/

POST {{url}}/api/ticket/ticket
content-type: application/json

{
    "precioTicket": 600,
    "categoriaEspectador": "E",
    "fechaCompra": "05/01/2024",
    "espectador" : "66720cbd9d0d4ec4a4f2198a",
    "categoria": "66720c2c8ddabf8da4cdc64c"
}

###

GET {{url}}/api/ticket/ticket
